name: Test Blocking Function

on:
  push:
    branches: [ main ]
    paths:
      - 'firebase-auth/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'firebase-auth/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase-auth/functions

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=$(pwd) python -m unittest discover -s tests -p "test_*.py" -v